### ISSUE TITLE
Paper Download

### ISSUE THREAD

**Issue by rain2050** [yuanhui0325/PCAC_GAN#1]
Thank you for your excellent work on open source.
I can't seem to find your paper online, is it available for study and reference?
I'm looking forward to hearing back from you.

**Comment by yuanhui0325** [comment]
[PCAC_GAN__A_Sparse_Tensor_Based_Generative_Adversarial_Network_for_3D_Point_Cloud_Attribute_Compression.pdf](https://github.com/yuanhui0325/PCAC_GAN/files/14755562/PCAC_GAN__A_Sparse_Tensor_Based_Generative_Adversarial_Network_for_3D_Point_Cloud_Attribute_Compression.pdf)
The paper has been accepted but has not been published yet. Please refer to the attached file.

**Comment by rain2050** [comment]
Thank you very much and wish you a happy life.
