### ISSUE TITLE
There is no "model" module.

### ISSUE THREAD

**Issue by rain2050** [yuanhui0325/PCAC_GAN#2]
Thank you Open Source for your excellent work.
While reproducing your code, I encountered some problems. There is no "model" module.
Do you have any further open-source plans?
Looking forward to your reply.

**Comment by yuanhui0325** [comment]
In the README, we provided trained models that can be downloaded.

**Comment by rain2050** [comment]
Thank you for getting back to me.
Yes, the reproduction and testing of your work still suggest that there is no 'model.py' file. Is reproducing and testing your work impossible without the 'model.py' file?

![1711952534350](https://github.com/yuanhui0325/PCAC_GAN/assets/39472362/75312462-68bf-4338-b480-38ef30a36701)

**Comment by yuanhui0325** [comment]
Sorry for the confusion, I will recheck the code and upload it again.

**Comment by rain2050** [comment]
Thank you very much and wish you good luck in your work.

**Comment by zb12138** [comment]
Same problem!

**Comment by yuanhui0325** [comment]
We trained seven models with seven different parameters. https://pan.baidu.com/s/1h-xs_orDr6CEdggOlVOAOA code：ABCD



> Same problem!
We trained seven models with seven different parameters. https://pan.baidu.com/s/1h-xs_orDr6CEdggOlVOAOA code：ABCD

**Comment by zb12138** [comment]
Yes, I have downloaded them, but then I met this problem.

**Comment by yuanhui0325** [comment]
> Yes, I have downloaded them, but then I met this problem.

I have reuploaded the pretrained models and updated some code , sorry for the trouble.

**Comment by rain2050** [comment]
Thank you for updating your code, but it seems that there is still a problem, as shown below. 

**Traceback (most recent call last):
  File "/home/rain/PCAC-GAN/main.py", line 10, in <module>
    from trainer import Trainer
  File "/home/rain/PCAC-GAN/trainer.py", line 5, in <module>
    from data_loader import PointCloudDataset
ImportError: cannot import name 'PointCloudDataset' from 'data_loader' (/home/rain/PCAC-GAN/data_loader.py)**

Also, the readme says to run "python trainer.py --dataset='training_dataset_rootdir'", but it seems to be running the main.py file.

**Comment by yuanhui0325** [comment]
> Thank you for updating your code, but it seems that there is still a problem, as shown below.
> 
> **Traceback (most recent call last): File "/home/rain/PCAC-GAN/main.py", line 10, in from trainer import Trainer File "/home/rain/PCAC-GAN/trainer.py", line 5, in from data_loader import PointCloudDataset ImportError: cannot import name 'PointCloudDataset' from 'data_loader' (/home/rain/PCAC-GAN/data_loader.py)**
> 
> Also, the readme says to run "python trainer.py --dataset='training_dataset_rootdir'", but it seems to be running the main.py file.

You can contact me at sduxlmao@gmail.com in order to give you a more detailed answer.

**Comment by yuanhui0325** [comment]
> Thank you for updating your code, but it seems that there is still a problem, as shown below.
> 
> **Traceback (most recent call last): File "/home/rain/PCAC-GAN/main.py", line 10, in from trainer import Trainer File "/home/rain/PCAC-GAN/trainer.py", line 5, in from data_loader import PointCloudDataset ImportError: cannot import name 'PointCloudDataset' from 'data_loader' (/home/rain/PCAC-GAN/data_loader.py)**
> 
> Also, the readme says to run "python trainer.py --dataset='training_dataset_rootdir'", but it seems to be running the main.py file.

You can use following code tp add the path to your script and debug the issue, and double check the moudle name.
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
